### ISSUE TITLE
Add same site accessor to servlet api

### ISSUE THREAD

**Issue by fabianfrz** [eclipse-ee4j/jakartaee-platform#284] opened 2020-12-02 12:26 UTC
**Is your feature request related to a problem? Please describe.**

Currently browsers block cookies cross domain if the flag samesite=none and secure are not set. For that reason, we loose the authentication sate.

**Describe the solution you'd like**

Class:  jakarta.servlet.http.Cookie 
Add accessor String getSameSite() and void setSameSite(String) to allow setting the flag

web.xml
```
    <cookie-config>
    	<http-only>true</http-only>
        <secure>true</secure>
        <same-site>none</same-site>
    </cookie-config>
```

**Describe alternatives you've considered**

* Use a servlet filter to use Set-Cookie headers to bypass the servlet api limitations
* Intercept responses on a proxy and rewrite the Set-Cookie headers

-> this is non-standard and should not be done in my opinion

**Comment by chkal** [comment] 2020-12-05 09:55
See: https://github.com/eclipse-ee4j/servlet-api/issues/175

**Comment by fabianfrz** [comment] 2020-12-06 20:58
@chkal thanks for oyur info, so I think we can close that one as duplicate?

**Comment by kwsutter** [comment] 2020-12-10 17:12
@fabianfrz We should actually close this Issue as a duplicate of https://github.com/eclipse-ee4j/servlet-api/issues/175.  The Servlet API is owned and developed by the servlet-api team, not the jakartaee-platform team.  Thanks!

**Closed by kwsutter** 2020-12-10 17:12 UTC
